momono_selfcare:
    resource: "@MomonoSelfcareBundle/Resources/config/routing.yml"
    prefix:   /

momono_front:
    resource: "@MomonoFrontBundle/Resources/config/routing.yml"
    prefix:   /

momono_default:
    resource: "@MomonoDefaultBundle/Resources/config/routing.yml"
    prefix:   /

momono_backoffice:
    resource: "@MomonoBackofficeBundle/Resources/config/routing.yml"
    prefix:   /
