momono_front:
    resource: "@MomonoFrontBundle/Resources/config/routing.yml"
    prefix:   /

momono_default:
    resource: "@MomonoDefaultBundle/Resources/config/routing.yml"
    prefix:   /

momono_backoffice:
    resource: "@MomonoBackofficeBundle/Resources/config/routing.yml"
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"