security:
    encoders:
        Momono\BackofficeBundle\Entity\Admin:
            algorithm:        sha1
            encode_as_base64: false
            iterations:       1

    role_hierarchy:
        ROLE_SELFCARE:      ROLE_USER
        ROLE_ADMIN:         ROLE_USER
        ROLE_SUPER_ADMIN:   ROLE_ADMIN

    providers:
        adminbundle:
            entity: { class: MomonoBackofficeBundle:Admin }
        userbundle:
            entity:
                class: Momono\DefaultBundle\Entity\User
                property: email

    firewalls:
        admin:
            # host: ^backoffice\.example\.com$
            pattern: ^/admin
            form_login:
                use_forward: false
                username_parameter: backoffice_login[username]
                password_parameter: backoffice_login[password]
                # do not allow GET
                post_only: true
                provider: adminbundle
                #csrf_provider: form.csrf_provider
                intention: authenticate
                check_path: /admin/login_check
                login_path: /admin/login
            logout:       
                path:   /logout
                target: /
            anonymous:    true            
        selfcare:
            pattern: ^/selfcare
            form_login:
                username_parameter: selfcare_login[username]
                password_parameter: selfcare_login[password]
                provider: userbundle
                csrf_provider: form.csrf_provider
                check_path: /selfcare/login_check
                login_path: selfcare_user_login
            logout:       true
            anonymous:    true
            remember_me:
                key:      "%secret%"
                lifetime: 31536000 # 365 jours en secondes
                path:     /
                domain:   ~
    access_control:
        - { path: ^/admin/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }
        - { path: ^/selfcare/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/selfcare/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/selfcare/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/selfcare/, role: ROLE_SELFCARE }