backoffice_login:
    pattern:   /admin/login
    defaults:  { _controller: MomonoBackofficeBundle:Security:login }
backoffice_login_check:
    pattern:   /admin/login_check
backoffice_logout:
    pattern:   /admin/logout

admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin
